---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - kevinapp.kevin.com
  resources:
  - nginxkevins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kevinapp.kevin.com
  resources:
  - nginxkevins/finalizers
  verbs:
  - update
- apiGroups:
  - kevinapp.kevin.com
  resources:
  - nginxkevins/status
  verbs:
  - get
  - patch
  - update
