# permissions for end users to edit houchangzaoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: houchangzao-editor-role
rules:
- apiGroups:
  - ingressapp.baiding.tech
  resources:
  - houchangzaoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ingressapp.baiding.tech
  resources:
  - houchangzaoes/status
  verbs:
  - get
