# permissions for end users to view houchangzaoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: houchangzao-viewer-role
rules:
- apiGroups:
  - ingressapp.baiding.tech
  resources:
  - houchangzaoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ingressapp.baiding.tech
  resources:
  - houchangzaoes/status
  verbs:
  - get
